In [ ]:
ss={"aman", "222", 777, 400.4}
t=tuple(ss)
print(t)

('aman', 777, 400.4, '222')


In [1]:
ss={"roll no" : "cse20263",
    "firstname": "Srinath",
    "lastname": "Palaniappan",
    "dob": "22-01-2003"}
print(ss)

{'roll no': 'cse20263', 'firstname': 'Srinath', 'lastname': 'Palaniappan', 'dob': '22-01-2003'}


In [ ]:
import numpy as np
from numpy import random
np.random.seed(5)
x=random.randint(20,size=(2,3))
print(x)


[[ 3 14 15]
 [ 6 16  9]]


In [ ]:
import random
print(random.uniform(0.0, 1.0))


0.5171785568557263


In [ ]:
t = random.randint(20,90)
print(t)

58


In [ ]:
pop = [11,12,13,14,15]
np.random.shuffle(pop)
print(pop)
print(pop[random.randint(0,5)])
temp=[pop.pop(random.randint(0,5)),pop.pop(random.randint(0,4)),pop.pop(random.randint(0,3))]
print(temp)

[12, 15, 13, 11, 14]
15
[15, 11, 14]


In [ ]:
f = open('test.txt','w')
f.write('The King is Dead, Long Live The King')
f.close()
f = open('test.txt','r')
for i in f:
  print(i,end=" ")
f.close()

The King is Dead, Long Live The King 

In [ ]:
dd="The King is Dead, Long Live The King"
print(dd)

The King is Dead, Long Live The King


In [ ]:
print(dd[0:1])
print(dd[2:5])
print(dd[2:])

T
e K
e King is Dead, Long Live The King


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr[1])
print(len(arr))

[4 5 6]
2


In [ ]:
import numpy as np
my_list = [1,2,3]
arr= np.array(my_list)
print(arr)


[1 2 3]


In [ ]:
def _sum(arr):
    sum = 0
    for i in arr:
        sum = sum + i
    return(sum)
arr = []
arr = [12, 3, 4, 15]
n = len(arr) 
ans = _sum(arr)
print('Sum of the array is ', ans)

Sum of the array is  34


In [ ]:
n_num = [2,1,9,1,2,22,1,1,4,55,6,2,56]
n = len(n_num)
  
get_sum = sum(n_num)
mean = get_sum / n
  
print("Mean is: " + str(mean))

Mean is: 12.461538461538462


In [ ]:
if n % 2 == 0:
    median1 = n_num[n//2]
    median2 = n_num[n//2 - 1]
    median = (median1 + median2)/2
else:
    median = n_num[n//2]
print("Median is: " + str(median))

Median is: 1


In [ ]:
max = arr[0];    
     
#Loop through the array    
for i in range(0, len(arr)):    
    #Compare elements of array with max    
   if(arr[i] > max):    
       max = arr[i];    
           
print("Largest element present in given array: " + str(max));   